name: Building Website Worker

on:
  push:
    branches:
      - main
      - master

jobs:
  build_worker:
    name: Build Worker
    env:
      NEWS_API: ${{ secrets.NEWS_API }}
      FETCH_BBTA3_URL: ${{ secrets.FETCH_BBTA3_URL }}
      FETCH_BPPT_URL: ${{ secrets.FETCH_BPPT_URL }}
      FETCH_VIDEO_URL: ${{ secrets.FETCH_VIDEO_URL }}
      SAVE_PATH: ${{ secrets.SAVE_PATH }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest Version
        uses: actions/checkout@v2
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build Worker Using Cargo
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Upload Website Worker to Release
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: worker
          files: target/release
          allow_override: true

  update_release_draft:
    name: Update Release Draft
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
