name: Uploading Release Asset

on:
  push:
    tags:
    - '*'

jobs:
  build_worker:
    name: Build Worker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest Version
        uses: actions/checkout@v2
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_NEWS_API: ${{ secrets.NEWS_API }}
          envkey_FETCH_BBTA3_URL: ${{ secrets.FETCH_BBTA3_URL }}
          envkey_FETCH_BPPT_URL: ${{ secrets.FETCH_BPPT_URL }}
          envkey_FETCH_VIDEO_URL: ${{ secrets.FETCH_VIDEO_URL }}
          envkey_SAVE_PATH: ${{ secrets.SAVE_PATH }}
      - name: Build Worker Using Cargo
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Upload Website Worker to Release
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: target/release
          allow_override: true
